project:
  type: website
  output-dir: docs

website:
  title: "Luke Ozsanlav-Harris"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Projects.qmd
      - href: Publications.qmd
      - href: CV.qmd
      - href: Maps.qmd
    right:
      - icon: github
        href: https://github.com/LukeOzsanlav
      - icon: google
        href: https://scholar.google.com/citations?user=9VyBol4AAAAJ&hl=en
      - icon: twitter
        href: https://twitter.com/Luke_ozharris
      - icon: envelope
        aria-label: email
        href: "mailto:lo288@exeter.ac.uk"
        
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

