project:
  type: website
  output-dir: docs

website:
  title: "LukeOzHarris"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Publications.qmd
    right:
      - icon: github
        href: https://github.com/LukeOzsanlav
      - icon: twitter
        href: https://twitter.com
        
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

