---
title: "CV"
github: https://github.com/LukeOzsanlav
---

## Skills Summary

**Analysis:** Statistical Modelling \| Spatial Data Analysis \| Biologging Data

**Software:** R \| Shiny \| QGIS \| Git \| Google Earth Engine

**Writing:** Scientific \| Technical Reports \| Public Communication

**Interpersonal:** Stakeholder Engagement \| Collaboration \| Workshop Facilitation

## Education

**PhD Biological Sciences, University of Exeter, 2019-2023**

Dissertation: Understanding the decline of a long-distance migratory bird, The Greenland White-fronted Goose; Supervisors: Prof Stuart Bearhop & Dr Geoff Hilton

**MSc Applied Ecology, University of Exeter, 2017-18 (Distinction)**

Dissertation: Understating the genetic basis of colour polymorphism in the green peach aphid Myzus persicae

**BSc Natural Sciences, University of Durham, 2014-2017** (2:1)

## Employment

**2022/23: Research Officer, Wildfowl and Wetland Trust** (October 2022 -- April 2023)

-   Publish work carried out during my PhD in scientific journals.
-   Manage and curate waterfowl tracking data sets, including upload to Movebank. - Write guide to help researchers with the processing and visualisation of animal tracking data in R.

**2022: JNCC Consultancy, Review of avoidance rates for collision risk modelling of seabirds** (Analyst and report lead author, Jan-Feb 2022.)

-   Review of available literature that measured seabird collisions with turbines.
-   Recalculation of avoidance rates in R and sensitivity analysis to test the effect of various input parameters.
-   Updated avoidance rates were included in a technical report and results explained to marine scientist and wind farm industry stakeholders.

**2021: MarPAMM funded project, Isle of Rum Manx Shearwater census** (Lead spatial analyst and fieldworker, May-June 2021)

-   Led spatial analysis for the final population estimate; manipulated Sentinel images and digital elevation models to build a predictive spatially explicit model that calculated burrow nesting bird density over the entire colony.
-   Surveyed the Manx Shearwater colony, carrying out habitat and burrow occupancy surveys.

## Research skills

**Data Analysis**

-   Curating large animal tracking database (\>250 million data points), including integration with Movebank.
-   Download, manipulation and analysis of remote sensing data, e.g. MODIS, Sentinel, ECMFW and NCEP.
-   Analysing animal movement data, e.g. Hidden Markov models, change point analysis, continuous time movement modelling and habitat selection analysis (RSFs & iSSFs).
-   Statistical analysis including; generalized mixed effects models incorporating spatial/temporal autocorrelation and time to event/survival modelling.
-   Machine learning analysis, e.g. classifying accelerometer data using random forests.
-   Spatial data manipulation and analysis in QGIS and R (using sf package).

**Fieldwork**

-   Assisted with the capture of large birds and the deployment of tracking devices on waterfowl and seabirds.
-   Organised logistics for teams to catch birds and deploy biologging devices.
-   Fieldwork in remote and challenging environment, e.g. surveys on Isle of Rum and Borneo.

**Collaboration**

-   Carrying out research with multiple partners, e.g. Wildfowl and wetlands trust, JNCC, BTO & Nature Scot.
-   Engagement with local stakeholders, particularly rural farmers on Islay, Scotland while researching contentious goose management cull

## Scientific Communication

**Goose News:** magazine-style article on the research carried out during my PhD research to a broader non-academic audience.

**Funding partner blog posts:** multiple blog posts for a funding partner website (Glengoyne distillery), conveying the findings of my research to their customers, example [here](https://www.glengoyne.com/news/productive-year-greenland-white-fronted-geese).

## Training

**Short course on analysing animal tracking data:** exploring movement characteristics, resource selection functions, integrated step selection functions, integrating environmental data.

**R shiny course:** Building R shiny apps, made app to fit Hidden Markov models to tracking data.

**Statistical analysis with R:** data manipulation, data visualisation, linear regression, generalised linear models, mixed effects models.

## Conferences/Presentations

-   **Invited seminar talk:** Understanding the decline of the Islay population of Greenland White-fronted Geese. *Scottish Goose Forum. Jan 2024.*

-   **Invited seminar talk:** Differing drivers of decline within a metapopulation has implications for future species conservation. *University of Lund. October 2022.*

-   **Talk:** Remotely understanding population decline in a high-arctic nesting goose. *University of Exeter, Centre for Ecology and Conservation symposium. March 2021.*

-   **Poster:** Differing demographic drivers of low reproductive success within a high artic migrant meta-population. *BOU avian reproduction conference. April 2022.*

-   Attended online conferences: BOU Global flyways (2023), BOU birds and people (2021), International biologging symposium (2021)

## Teaching

**Rewilding field course, Scotland** (teaching and logistics): Teaching assistant on MSc field course organising logistics and gave talks to student on my PhD research.

**Applications of biologging data** (undergraduate practical): Designed material and delivered an undergraduate practical to demonstrate the potential applications of biologging data. Built shiny app that allows users to explore cleaning/preparation of tracking data for analysis.
